name: Publish site

on:
  push:
    tags:
      - '*'
  schedule:
      - cron: "0 */6 * * *"

jobs:
  publish-site:
    runs-on: ubuntu-18.04
    env:
      TARGET: ${{ secrets.TARGET_SITE }}

    steps:
      - uses: actions/checkout@v1

      - run: cat > id_rsa <<< "${{ secrets.ID_RSA }}"
             && chmod og-rw id_rsa

      - run: make get-state update html push-state

      - run: git diff
