name: Publish site

on:
  push:
    tags:
      - '*'
  schedule:
      - cron: "0 */3 * * *"

jobs:
  publish-site:
    runs-on: ubuntu-18.04
    env:
      TARGET: ${{ secrets.TARGET_SITE }}
      POST:   ${{ secrets.POST }}

    steps:
      - uses: actions/checkout@v1

      - run: sudo timedatectl set-timezone Europe/Paris

      - run: make get-state update html push-state

      - run: git diff
